### ISSUE TITLE
请教extender的用法

### ISSUE THREAD

**Issue by qwurey** [gaocegege/simple-k8s-scheduler-extender#1]
请教一下，extender用法是在所有配置的priorities后面，再经过这个extender的策略吗？
比如经过priorities后，出来3个node，分数分别为10，9，8，再经过extender后，分数变为3，7，8；那么最后返回node3？
谢谢~！

**Comment by gaocegege** [comment]
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/generic_scheduler.go#L247:#L381

读读就知道了 :)

**Comment by qwurey** [comment]
谢谢~！


2016-11-28 14:43 GMT+08:00 Ce Gao <notifications@github.com>:

**Comment by gaocegege** [comment]
If you have other questions, feel free to send me a email, I would close this issue now :)
